### ISSUE TITLE
Bug: chewrec_func cannot be set

### ISSUE THREAD

**Issue by avniculae** [tmetsch/python-dtrace#27]
Hi,

Both `DTraceConsumer` and `DTraceContinuousConsumer` constructors fail to correctly set the `chewrec_func`. As a consequence, the bug is also present in `DTraceConsumerThread`. The following lines should use `chewrec_func` instead of `simple_chewrec`:

https://github.com/tmetsch/python-dtrace/blob/56101d6d07d736c7041b0838bb138c3bfed25a81/dtrace_cython/consumer.pyx#L310

https://github.com/tmetsch/python-dtrace/blob/56101d6d07d736c7041b0838bb138c3bfed25a81/dtrace_cython/consumer.pyx#L435 

Not sure if other changes are needed.

**Comment by tmetsch** [comment]
Ah good point, will look into this asap - Thanks for reporting!

**Comment by tmetsch** [comment]
I think this was introduces by issue #21 - will test this now.

**Comment by tmetsch** [comment]
Fixed in 0.0.15
