### ISSUE TITLE
Cython version leaks all handles

### ISSUE THREAD

**Issue by jrtc27** [tmetsch/python-dtrace#8]
In the Cython version, the handles are closed in `__del__` both for DTraceConsumer and DTraceContinuousConsumer (used by DTraceConsumerThread). However, these are extension types, and Cython [does not use `__del__` for extension types][1] (for whatever reason), so they will never be called (the explicit `del self.consumer` in DTraceConsumerThread's destructor, which *is* called as it's a normal Python object, just ensures the DTraceContinuousConsumer gets deallocated, but the consumer's `__del__` still won't be called). I believe using `__dealloc__` for the two extension classes would work (though `handle` must be checked for being non-null first).

This has also exposed a (minor) potential issue: with Cython, [`__init__` can end up being called multiple times][2], so technically `handle` could be initialised twice, leaking the old return from `dtrace_open`. To be truly correct, either `__init__` should guard against this, or `__cinit__` should be used instead, which will only ever be called once.

[1]: http://docs.cython.org/en/latest/src/userguide/special_methods.html#finalization-method-dealloc
[2]: http://docs.cython.org/en/latest/src/userguide/special_methods.html#initialisation-methods-cinit-and-init

**Comment by jrtc27** [comment]
In fact it's even worse for DTraceContinuousConsumer, as that only calls `dtrace_close` in `__del__`, so the script will keep running (until the Python process exits).

**Comment by tmetsch** [comment]
Thanks for reporting these findings... (y)

You are right, will need to look into this and properly clean-up after we are done consuming. Did you by any chance, made the changes needed yet? If so can you make open a push request?

**Comment by tmetsch** [comment]
Took a stab at this, based on your proposals. See: https://github.com/tmetsch/python-dtrace/commit/8fdd42537affe1f44b35b45a092ea91dc8d46b2f

**Comment by jrtc27** [comment]
Great, that looks like what I was thinking of, except it's `__dealloc__`, not `__delalloc__`.
